// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm36aoda0VPD7jmT2s3RB_j9dltfNXJ6w',
    appId: '1:945258803127:web:d8364cab7b3d8b2d8a4232',
    messagingSenderId: '945258803127',
    projectId: 'oceanaguasol',
    authDomain: 'oceanaguasol.firebaseapp.com',
    storageBucket: 'oceanaguasol.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOXwViwm63GHkP-FIrK8xoH7GPKP_XGI',
    appId: '1:945258803127:android:0b60f9127d1fdb1b8a4232',
    messagingSenderId: '945258803127',
    projectId: 'oceanaguasol',
    storageBucket: 'oceanaguasol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVshiZukEkvcmHeDt0vbHHJZCAmMbpkE',
    appId: '1:945258803127:ios:6f3a0d9205d803748a4232',
    messagingSenderId: '945258803127',
    projectId: 'oceanaguasol',
    storageBucket: 'oceanaguasol.appspot.com',
    iosBundleId: 'com.example.appsolFinal',
  );
}
